package nl.ulso.curator.addon.journal;

import dagger.Binds;
import dagger.Module;
import dagger.multibindings.IntoSet;
import nl.ulso.curator.change.ChangeProcessor;
import nl.ulso.curator.query.Query;
import nl.ulso.curator.statistics.MeasurementTracker;

/// Extracts journal information from daily logs.
///
/// The journal is extracted from a specific H2 section in the daily log pages, as configured in the
/// constructor. That section is expected to contain an outline: a nested list of items that
/// describe the things to log for that day.
///
/// Once the log is built, it's possible to extract information for it, like a timeline for a
/// specific referenced document. That timeline contains, for each day the document is referenced, a
/// subset of the outline.
///
/// This journal is inspired heavily by Logseq, except of course that output generated by this tool
/// is statically included in Markdown files, instead of dynamic.
///
/// To use this journal in your own curator, you have to install it in your Dagger module.
@Module
public abstract class JournalModule
{
    @Binds
    abstract JournalMessages bindJournalMessages(ResourceBundleJournalMessages messages);

    @Binds
    @IntoSet
    abstract ChangeProcessor bindDailyProducer(DailyProducer dailyProducer);

    @Binds
    @IntoSet
    abstract ChangeProcessor bindDailyProcessor(DefaultDailyRepository dailyRepository);

    @Binds
    abstract DailyRepository bindDailyRepository(DefaultDailyRepository dailyRepository);

    @Binds
    @IntoSet
    abstract MeasurementTracker bindDailyMeasurements(DefaultDailyRepository dailyRepository);

    @Binds
    @IntoSet
    abstract ChangeProcessor bindWeeklyProducer(WeeklyProducer weeklyProducer);

    @Binds
    @IntoSet
    abstract ChangeProcessor bindWeeklyProcessor(DefaultWeeklyRepository weeklyRepository);

    @Binds
    abstract WeeklyRepository bindWeeklyRepository(DefaultWeeklyRepository weeklyRepository);

    @Binds
    @IntoSet
    abstract MeasurementTracker bindWeeklyMeasurements(DefaultWeeklyRepository weeklyRepository);

    @Binds
    @IntoSet
    abstract ChangeProcessor bindMarkerProducer(MarkerProducer markerProducer);

    @Binds
    @IntoSet
    abstract ChangeProcessor bindMarkerProcessor(DefaultMarkerRepository markerRepository);

    @Binds
    abstract MarkerRepository bindMarkerRepository(DefaultMarkerRepository markerRepository);

    @Binds
    @IntoSet
    abstract MeasurementTracker bindMarkerMeasurements(DefaultMarkerRepository markerRepository);

    @Binds
    abstract Journal bindJournal(DefaultJournal journal);

    @Binds
    @IntoSet
    abstract Query bindTimelineQuery(TimelineQuery timelineQuery);

    @Binds
    @IntoSet
    abstract Query bindPeriodQuery(PeriodQuery periodQuery);

    @Binds
    @IntoSet
    abstract Query bindWeeklyQuery(WeeklyQuery weeklyQuery);

    @Binds
    @IntoSet
    abstract Query bindDayNavigationQuery(DayNavigationQuery dayNavigationQuery);

    @Binds
    @IntoSet
    abstract Query bindWeekNavigationQuery(WeekNavigationQuery weekNavigationQuery);

    @Binds
    @IntoSet
    abstract Query bindLatestJournalNavigationQuery(LatestJournalNavigationQuery markedQuery);

    @Binds
    @IntoSet
    abstract Query bindMarkedQuery(MarkedQuery markedQuery);
}
