package nl.ulso.markdown_curator.journal;

import com.google.inject.AbstractModule;
import com.google.inject.Provides;
import com.google.inject.multibindings.Multibinder;
import nl.ulso.markdown_curator.DataModel;
import nl.ulso.markdown_curator.query.Query;

import java.time.temporal.WeekFields;

import static com.google.inject.multibindings.Multibinder.newSetBinder;

/**
 * Extracts journal information from daily logs.
 * <p/>
 * The journal is extracted from a specific H2 section in the daily log pages, as configured in the
 * constructor. That section is expected to contain an outline: a nested list of items that describe
 * the things to log for that day.
 * <p/>
 * Once the log is built, it's possible to extract information for it, like a timeline for a
 * specific referenced document. That timeline contains, for each day the document is referenced
 * a subset of the outline.
 * <p/>
 * This journal is inspired heavily by Logseq, except of course that output generated by this tool
 * is statically included in Markdown files, instead of dynamic.
 * <p/>
 * To use this journal in your own curator, you have to do install it in your Guice module.
 */
public class JournalModule
        extends AbstractModule
{
    private final String journalFolder;
    private final String activitiesSection;
    private final String projectFolder;
    private final WeekFields weekFields;

    public JournalModule(String journalFolder, String activitiesSection, String projectFolder)
    {
        this(journalFolder, activitiesSection, projectFolder, WeekFields.ISO);
    }

    public JournalModule(String journalFolder, String activitiesSection, String projectFolder, WeekFields weekFields)
    {
        this.journalFolder = journalFolder;
        this.activitiesSection = activitiesSection;
        this.projectFolder = projectFolder;
        this.weekFields = weekFields;
    }

    @Provides
    JournalSettings journalSettings()
    {
        return new JournalSettings(journalFolder, activitiesSection, projectFolder, weekFields);
    }

    @Override
    protected void configure()
    {
        newSetBinder(binder(), DataModel.class).addBinding().to(Journal.class);
        Multibinder<Query> queryBinder = newSetBinder(binder(), Query.class);
        queryBinder.addBinding().to(TimelineQuery.class);
        queryBinder.addBinding().to(PeriodQuery.class);
        queryBinder.addBinding().to(WeeklyQuery.class);
        queryBinder.addBinding().to(DayNavigationQuery.class);
        queryBinder.addBinding().to(WeekNavigationQuery.class);
    }
}

